language: java

jdk:
  - oraclejdk14

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod +x ./gradlew

script:
  - ./gradlew clean install
  - ./gradlew clean test